steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/miocardio-pediatra', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/miocardio-pediatra']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'miocardio-pediatra', '--image', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]', '--region', 'us-east1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/miocardio-pediatra